consul:
  image: kompaas
  net: host
  privileged: true
  command: "consul agent -client=0.0.0.0 -data-dir=/opt/consul/ -ui-dir=/dist/ -advertise=127.0.0.1 -dc=dc1 -server -bootstrap-expect 1"

nomad:
  image: kompaas
  net: host
  privileged: true
  command: "nomad agent -dev "
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

fabio:
  image: kompaas
  net: host
  privileged: true
  command: "fabio"
